version: 3

project:
  locator: SolaceProducts_solace-spring-boot
  id: SolaceProducts_solace-spring-boot
  name: solace-spring-boot
  teams: []
  labels:
    - java

vendoredDependencies:
  forceRescans: false
  scanMethod: CLILicenseScan
  licenseScanPathFilters:
    exclude:
      - "./.git"
      - "./.github"

paths:
  exclude:
    - ./.git
    - ./.github

telemetry:
  scope: full
