version: 3
project:
  locator: SolaceProducts_solace-jms-spring-boot-autoconfigure
  id: SolaceProducts_solace-jms-spring-boot-autoconfigure
  name: solace-jms-spring-boot-autoconfigure
  teams: []
  labels:
    - java
vendoredDependencies:
  forceRescans: false
  scanMethod: CLILicenseScan
  licenseScanPathFilters:
    exclude:
      - "./.git"
      - "./.github"
paths:
  exclude:
    - ./.git
    - ./.github
telemetry:
  scope: full
